services:
  app:
    image: 'canopus-messaging:0.0.1'
    container_name: canopus-messaging
    build: '.'
    ports:
      - "8085:8080"
      - "5005:5005"
    networks:
      - canopus
    volumes:
      - ~/canopus/fs_content:/var/lib/content
networks:
  canopus:
    name: canopus